services:
    server:
        image: nginx:alpine
        restart: unless-stopped
        container_name: back_nginx
        ports:
            - 8081:80
        networks:
            - app-network
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/

    app:
        build: .
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - ./:/var/www
    mariadb:
        image: mariadb
        container_name: misterfantasy_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - app-network
        ports:
            - "3306:3306"
        volumes:
            - /home/ubuntu/compose/mariadb_backup:/datos


networks:
    app-network:
        driver: bridge
